=== daftpunk6161/Sortierung/data/schemas/dat-catalog.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://romulus.local/schemas/dat-catalog.schema.json",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["Id", "System", "Format"],
    "properties": {
      "Id": { "type": "string", "minLength": 1 },
      "System": { "type": "string", "minLength": 1 },
      "Format": {
        "type": "string",
        "enum": ["raw-dat", "zip-dat", "7z-dat", "nointro-pack"]
      },
      "Group": { "type": ["string", "null"] },
      "PackMatch": { "type": ["string", "null"] },
      "Url": { "type": ["string", "null"] },
      "ConsoleKey": { "type": ["string", "null"] }
    },
    "additionalProperties": false
  }
}

=== daftpunk6161/Sortierung/data/dat-catalog.json
[
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/3do/",
    "System": "3DO Interactive Multiplayer",
    "Id": "redump-3do",
    "ConsoleKey": "3DO",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/acd/",
    "System": "Acorn - Archimedes CD",
    "Id": "redump-acd",
    "ConsoleKey": "ACD",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/cd32/",
    "System": "Commodore - Amiga CD32",
    "Id": "redump-cd32",
    "ConsoleKey": "CD32",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/cdtv/",
    "System": "Commodore - Amiga CDTV",
    "Id": "redump-cdtv",
    "ConsoleKey": "CDTV",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/cdi/",
    "System": "Philips - CD-i",
    "Id": "redump-cdi",
    "ConsoleKey": "CDI",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/chihiro/",
    "System": "Sega - Chihiro",
    "Id": "redump-chihiro",
    "ConsoleKey": "CHI",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/dc/",
    "System": "Sega - Dreamcast",
    "Id": "redump-dc",
    "ConsoleKey": "DC",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/fmt/",
    "System": "Fujitsu - FM Towns",
    "Id": "redump-fmt",
    "ConsoleKey": "FMT",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/gc/",
    "System": "Nintendo - GameCube",
    "Id": "redump-gc",
    "ConsoleKey": "GC",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/hs/",
    "System": "Matsushita - Video Now Color",
    "Id": "redump-hs",
    "ConsoleKey": "HS",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/ksite/",
    "System": "Konami - e-Amusement",
    "Id": "redump-ksite",
    "ConsoleKey": "KSITE",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/lindbergh/",
    "System": "Sega - Lindbergh",
    "Id": "redump-lindbergh",
    "ConsoleKey": "LIND",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/mac/",
    "System": "Apple - Macintosh",
    "Id": "redump-mac",
    "ConsoleKey": "MAC",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/mcd/",
    "System": "Sega - Mega CD & Sega CD",
    "Id": "redump-mcd",
    "ConsoleKey": "MCD",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/naomi/",
    "System": "Sega - Naomi",
    "Id": "redump-naomi",
    "ConsoleKey": "NAOMI",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/naomi2/",
    "System": "Sega - Naomi 2",
    "Id": "redump-naomi2",
    "ConsoleKey": "NAO2",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/ngcd/",
    "System": "SNK - Neo Geo CD",
    "Id": "redump-ngcd",
    "ConsoleKey": "NEOCD",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/nuon/",
    "System": "VM Labs - NUON",
    "Id": "redump-nuon",
    "ConsoleKey": "NUON",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/palm/",
    "System": "Palm",
    "Id": "redump-palm",
    "ConsoleKey": "PALM",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/pc/",
    "System": "IBM - PC compatible",
    "Id": "redump-pc",
    "ConsoleKey": "IBMPC",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/pc-88/",
    "System": "NEC - PC-88 series",
    "Id": "redump-pc88",
    "ConsoleKey": "PC88",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/pc-98/",
    "System": "NEC - PC-98 series",
    "Id": "redump-pc98",
    "ConsoleKey": "PC98",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/pce/",
    "System": "NEC - PC Engine CD & TurboGrafx CD",
    "Id": "redump-pce-cd",
    "ConsoleKey": "PCECD",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/pc-fx/",
    "System": "NEC - PC-FX & PC-FXGA",
    "Id": "redump-pcfx",
    "ConsoleKey": "PCFX",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/photo-cd/",
    "System": "Photo CD",
    "Id": "redump-photo-cd",
    "ConsoleKey": "PCD",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/pippin/",
    "System": "Apple - Bandai Pippin",
    "Id": "redump-pippin",
    "ConsoleKey": "PIPPIN",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/psx/",
    "System": "Sony - PlayStation",
    "Id": "redump-ps1",
    "ConsoleKey": "PSX",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/ps2/",
    "System": "Sony - PlayStation 2",
    "Id": "redump-ps2",
    "ConsoleKey": "PS2",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/ps3/",
    "System": "Sony - PlayStation 3",
    "Id": "redump-ps3",
    "ConsoleKey": "PS3",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/psp/",
    "System": "Sony - PlayStation Portable",
    "Id": "redump-psp",
    "ConsoleKey": "PSP",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/ss/",
    "System": "Sega - Saturn",
    "Id": "redump-ss",
    "ConsoleKey": "SAT",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/vflash/",
    "System": "VTech - V.Flash & V.Smile Pro",
    "Id": "redump-vflash",
    "ConsoleKey": "VFLASH",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/wii/",
    "System": "Nintendo - Wii",
    "Id": "redump-wii",
    "ConsoleKey": "WII",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/xbox/",
    "System": "Microsoft - Xbox",
    "Id": "redump-xbox",
    "ConsoleKey": "XBOX",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/xbox360/",
    "System": "Microsoft - Xbox 360",
    "Id": "redump-xbox360",
    "ConsoleKey": "X360",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/ajcd/",
    "System": "Atari - Jaguar CD",
    "Id": "redump-ajcd",
    "ConsoleKey": "AJCD",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/gamewave/",
    "System": "ZAPiT - Game Wave",
    "Id": "redump-gamewave",
    "ConsoleKey": "GW",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/ite/",
    "System": "Incredible Technologies - Eagle",
    "Id": "redump-ite",
    "ConsoleKey": "ITE",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/ixl/",
    "System": "Mattel - Fisher-Price iXL",
    "Id": "redump-ixl",
    "ConsoleKey": "IXL",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/ppc/",
    "System": "Pocket PC",
    "Id": "redump-ppc",
    "ConsoleKey": "PPC",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/quizard/",
    "System": "TAB-Austria - Quizard",
    "Id": "redump-quizard",
    "ConsoleKey": "QUIZ",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/vis/",
    "System": "Memorex - Visual Information System",
    "Id": "redump-vis",
    "ConsoleKey": "VIS",
    "Format": "zip-dat"
  },
  {
    "Group": "Redump",
    "Url": "https://redump.org/datfile/x68k/",
    "System": "Sharp - X68000",
    "Id": "redump-x68k",
    "ConsoleKey": "X68K",
    "Format": "zip-dat"
  },
  {
    "Group": "No-Intro",
    "PackMatch": "Nintendo - Nintendo Entertainment System (Headered)*",
    "Url": "",
    "System": "Nintendo - NES",
    "Id": "nointro-nes",
    "ConsoleKey": "NES",
    "Format": "nointro-pack"
  },
  {
    "Group": "No-Intro",
    "PackMatch": "Nintendo - Super Nintendo Entertainment System*",
    "Url": "",
    "System": "Nintendo - SNES",
    "Id": "nointro-snes",
    "ConsoleKey": "SNES",
    "Format": "nointro-pack"
  },
  {
    "Group": "No-Intro",
    "PackMatch": "Nintendo - Nintendo 64 (BigEndian)*",
    "Url": "",
    "System": "Nintendo - N64",
    "Id": "nointro-n64",
    "ConsoleKey": "N64",
    "Format": "nointro-pack"
  },
  {
    "Group": "No-Intro",
    "PackMatch": "Nintendo - Game Boy Advance (Private)*",
    "Url": "",
    "System": "Nintendo - Game Boy Advance",
    "Id": "nointro-gba",
    "ConsoleKey": "GBA",
    "Format": "nointro-pack"
  },
  {
    "Group": "No-Intro",
    "PackMatch": "Nintendo - Game Boy (Private)*",
    "Url": "",
    "System": "Nintendo - Game Boy",
    "Id": "nointro-gb",
    "ConsoleKey": "GB",
    "Format": "nointro-pack"
  },
  {
    "Group": "No-Intro",
    "PackMatch": "Nintendo - Game Boy Color*",
    "Url": "",
    "System": "Nintendo - Game Boy Color",
    "Id": "nointro-gbc",
    "ConsoleKey": "GBC",
    "Format": "nointro-pack"
  },
  {
    "Group": "No-Intro",
    "PackMatch": "Nintendo - Nintendo DS (Decrypted)*",
    "Url": "",
    "System": "Nintendo - DS",
    "Id": "nointro-nds",
    "ConsoleKey": "NDS",
    "Format": "nointro-pack"
  },
  {
    "Group": "No-Intro",
    "PackMatch": "Sega - Mega Drive - Genesis*",
    "Url": "",
    "System": "Sega - Mega Drive / Genesis",
    "Id": "nointro-md",
    "ConsoleKey": "MD",
    "Format": "nointro-pack"
  },
